### ISSUE TITLE
Put the main endorsements on the README.md page

### ISSUE THREAD

**Issue by suchov** [kottans/kottans#9]
What do you think about small refactoring and putting the names on the main page - README
I think it would look more inspiring like that.
What do you think?

**Comment by OleksiyRudenko** [comment]
Makes sense. Not so much to show in `README.md`.
Need to take into consideration that some badges already issued lead to `endorsements.md`, so if we take badges to `README.md` then `endorsements.md` should contain some brief explanation why is it empty and a link to `README.md#endorsements`.

**Comment by suchov** [comment]
got it, maybe we should do it sooner than?
& keep endorsments.md ?
